#!/bin/sh

# Get the package.json version and the git tag version on main branch
VERSION="$(cat package.json | json version)"
GITTAG="$(git tag --points-at origin/main)"
MAINVERSION=${GITTAG//v/}

# If the versions are equal, this indicates this is just a change and not a release
# Patch the version and save it back to package.json
if [ "$VERSION" == "$MAINVERSION" ]
then
    NEWVERSION="$(semver --increment patch $VERSION)"
    json -I -f package.json -e "this.version=\"$NEWVERSION\""
    echo "package.json version patched: $(cat package.json | json version)"
fi

# If the versions are not equal, do nothing.
# This indicates a manual change in order to do a major or minor bump of the version for a release
# Or indicates that a previous commit already patched the version
