name: Unit Test

on:
  push:
    branches:
      # Push events to main
      - main
      # Push events to feature branches
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Build and Unit Test
        run: |
          npm install
          npm run build
          npm run test